// eslint-disable-next-line @typescript-eslint/no-require-imports
const sql = require("better-sqlite3");
const db = sql("holidays.db");

const holidays = [
  {
    // base
    image: "/images/maldives.jpg",
    slug: "maldives",
    country: "Malediwy",
    city: "Raa Atol",
    hotel_name: "You & Me by Cocoon Maldives",
    date: "22.11.2024 - 30.11.2024",
    departure_city: "Gdańsk",
    arrival_city: "Dubaj",
    food: "All Inclusive",
    rating: "5",
    price: 2137,
    // details
    hotel_features: "suszarka, żelazko, zmywarka",
    hotel_attractions: "leżak, kocyk, świeczki",
    hotel_image: "/images/maldives-hotel.jpg",
    holiday_description:
      "Fajna ciasna wycieczka na Malediwy. Tylko drogo troche. Ale będzie fajnie. Opalanko, słońce plaża przyjaciele.",
    hotel_description: "Chatka na wodzie. Zimno, wiatr wieje, podglądają.",
    food_details:
      "Śniadanie o 6 rano jak kokosa znajdziesz. O 15 obiad jak se coś upolujesz w lesie. O 19 kolacja przy świecach - śledzik",
  },
  {
    // base
    image: "/images/dubai.jpg",
    slug: "dubai",
    country: "Dubai",
    city: "Dubaj",
    hotel_name: "Rose Rayhaan Dubai",
    date: "16.08.2024 - 24.05.2024",
    departure_city: "Warszawa",
    arrival_city: "Dubaj",
    food: "All Inclusive",
    rating: "3",
    price: 1899,
    // details
    hotel_features: "suszarka, pralka, zmywarka, lodówka",
    hotel_attractions: "basen, pool bar, SPA",
    hotel_image: "/images/dubai.jpg",
    holiday_description:
      "Rekreacyjna wycoeczka do dubaju, słonko swieci, trzeba brać dobrego SPHAa",
    hotel_description: "Hotel ma bogate prześcieradła",
    food_details: "Jesz drogie homary i inne rekiny.",
  },
];

const oldHolidays = [
  {
    image: "/images/maldives.jpg",
    slug: "maldives",
    country: "You & Me by Cocoon Maldives",
    price: 2137.0,
    date: "16.08.2024 - 24.05.2024",
    departure_city: "Gdańsk",
    food: "All Inclusive",
    rating: "1",
    place: "Malediwy / Raa Atol / Raa Atol",
  },
  {
    image: "/images/dubai.jpg",
    slug: "dubai",
    country: "Rose Rayhaan Dubai",
    price: 1234.0,
    date: "16.08.2024 - 24.05.2024",
    departure_city: "Warszawa",
    food: "All Inclusive",
    rating: "4",
    place: "Emiraty Arabskie / Dubaj",
  },
  {
    image: "/images/madeira.jpg",
    slug: "madeira",
    country: "Dom Pedro Madera",
    price: 4321.0,
    date: "16.08.2024 - 24.05.2024",
    departure_city: "Gdańsk",
    food: "All Inclusive",
    rating: "5",
    place: "Portugalia / Madera / Machico",
  },
  {
    image: "/images/thailand.jpg",
    slug: "thailand",
    country: "Grande Resort Phuket",
    price: 5428.0,
    date: "31.03.2024 - 11.04.2024",
    departure_city: "Warszawa",
    food: "All Inclusive",
    rating: "5",
    place: "Tajlandia / Phuket / Grande Resort Phuket",
  },
  {
    image: "/images/china.jpg",
    slug: "china",
    country: "Chiny - dwie stolice",
    price: 11938.0,
    date: "09.02.2024 - 17.02.2024",
    departure_city: "Warszawa",
    food: "All Inclusive",
    rating: "5",
    place: "Chiny/ Wycieczka objazdowa / Pekin / Chiny - dwie stolice",
  },
  {
    image: "/images/barcelona.jpg",
    slug: "barcelona",
    country: "Hotel INNSiDE",
    price: 719.0,
    date: "16.08.2024 - 24.05.2024",
    departure_city: "Gdańsk",
    food: "Własne",
    rating: "4",
    place: "Hiszpania / Barcelona / Hotel INNSiDE",
  },
  {
    image: "/images/gdansk.jpg",
    slug: "gdansk",
    country: "IBB Hotel Gdańsk",
    price: 520.0,
    date: "16.08.2024 - 24.05.2024",
    departure_city: "Kraków",
    food: "All Inclusive",
    rating: "5",
    place: "Polska / Gdańsk / IBB Hotel Gdańsk",
  },
  {
    image: "/images/egypt.jpg",
    slug: "egypt",
    country: "Aladdin Beach Resort",
    price: 1932.0,
    date: "09.12.2023 - 16.12.2023",
    departure_city: "Warszawa",
    food: "All Inclusive Elite",
    rating: "5",
    place: "Egipt / Hurghada / Aladdin Beach Resort",
  },
  {
    image: "/images/kenia.jpg",
    slug: "kenya",
    country: "Diani Sea Lodge",
    price: 5739.0,
    date: "22.10.2024 - 29.10.2024",
    departure_city: "Katowice",
    food: "All Inclusive",
    rating: "3",
    place: "Kenia / Wybrzeże Mombasy / Diani Sea Lodge",
  },
  {
    image: "/images/losangeles.jpg",
    slug: "los-angeles",
    country: "Sunset Strip",
    price: 8525.0,
    date: "31.10.2023 - 09.11.2023",
    departure_city: "Warszawa",
    food: "All Inclusive",
    rating: "5",
    place: "USA / Kalifornia - Los Angeles / Sunset Strip",
  },
  {
    image: "/images/london.jpg",
    slug: "london",
    country: "W służbie Jego Królewskiej Mości",
    price: 5316.0,
    date: "01.06.2024 - 08.06.2024",
    departure_city: "Gdańsk",
    food: "All Inclusive",
    rating: "3",
    place:
      "Wielka Brytania / Wycieczka objazdowa / London / W służbie Jego Królewskiej Mości",
  },
  {
    image: "/images/miami.jpg",
    slug: "miami",
    country: "Holiday Inn Miami",
    price: 7395.0,
    date: "07.09.2024 - 15.09.2024",
    departure_city: "Warszawa",
    food: "Własne",
    rating: "5",
    place: "USA / Floryda / Holiday Inn Miami",
  },
  {
    image: "/images/paris.jpg",
    slug: "paris",
    country: "Vice Versa",
    price: 4149.0,
    date: "01.01.2024 - 08.01.2024",
    departure_city: "Wrocław",
    food: "All Inclusive",
    rating: "3",
    place: "Francja / Paryż / Vice Versa",
  },
  {
    image: "/images/new-york.jpg",
    slug: "new-york",
    country: "Midtown Times Square Hotel",
    price: 13158.0,
    date: "01.03.2024 - 07.03.2024",
    departure_city: "Kraków",
    food: "All Inclusive",
    rating: "4",
    place: "USA / Nowy Jork / Midtown Times Square Hotel",
  },
];

db.exec(`CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY,
  email TEXT UNIQUE,
  password TEXT
  )`);

db.exec(`CREATE TABLE IF NOT EXISTS sessions (
  id TEXT NOT NULL PRIMARY KEY,
  expires_at INTEGER NOT NULL,
  user_id TEXT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id)
  )`);

db.exec(`
  CREATE TABLE IF NOT EXISTS holidays (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    image TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    country TEXT NOT NULL,
    city TEXT NOT NULL,
    hotel_name TEXT NOT NULL,
    date TEXT NOT NULL,
    departure_city TEXT NOT NULL,
    arrival_city TEXT NOT NULL,
    food TEXT NOT NULL,
    rating TEXT NOT NULL,
    price INTEGER NOT NULL,
    hotel_features TEXT NOT NULL,
    hotel_attractions TEXT NOT NULL,
    hotel_image TEXT NOT NULL,
    holiday_description TEXT NOT NULL,
    hotel_description TEXT NOT NULL,
    food_details TEXT NOT NULL
  )`);

db.exec(`
  CREATE TABLE IF NOT EXISTS booked_holidays (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    holiday_id INTEGER NOT NULL,
    planned_holiday_id INTEGER,
    booking_name TEXT NOT NULL,
    booking_surname TEXT NOT NULL,
    booking_email TEXT NOT NULL,
    booking_phone TEXT NOT NULL,
    holiday_members TEXT NOT NULL,
    total_price INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
    FOREIGN KEY (holiday_id) REFERENCES holidays(id)
    FOREIGN KEY (planned_holiday_id) REFERENCES planned_holidays(id)
  )`);

db.exec(`
  CREATE TABLE IF NOT EXISTS planned_holidays (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    booked_holiday_id INTEGER NOT NULL,
    main_budget INTEGER NULL,
    insurance_budget INTEGER NULL,
    shopping_budget INTEGER NULL,
    souvenirs_budget INTEGER NULL,
    activities_budget INTEGER NULL,
    food_budget INTEGER NULL,
    has_local_cash INTEGER NULL,
    has_visa INTEGER NULL,
    has_insurance INTEGER NULL,
    has_vaccinations INTEGER NULL,
    has_passport INTEGER NULL,
    has_id_card INTEGER NULL,
    has_tickets INTEGER NULL,
    has_travel_invitation INTEGER NULL,
    has_intl_driving_license INTEGER NULL,
    has_payment_card INTEGER NULL,
    has_tshirts INTEGER NULL,
    has_pants INTEGER NULL,
    has_underwear INTEGER NULL,
    has_shoes INTEGER NULL,
    has_jacket INTEGER NULL,
    has_raincoat INTEGER NULL,
    has_flip_flops INTEGER NULL,
    has_headwear INTEGER NULL,
    has_toothbrush INTEGER NULL,
    has_toothpaste INTEGER NULL,
    has_dental_floss INTEGER NULL,
    has_shampoo INTEGER NULL,
    has_conditioner INTEGER NULL,
    has_hair_mask INTEGER NULL,
    has_shower_gel INTEGER NULL,
    has_soap INTEGER NULL,
    has_deodorant INTEGER NULL,
    has_perfume INTEGER NULL,
    has_moisturizer INTEGER NULL,
    has_spf_cream INTEGER NULL,
    has_after_sun_cream INTEGER NULL,
    has_razor INTEGER NULL,
    has_shaving_foam INTEGER NULL,
    has_brush INTEGER NULL,
    has_hair_accessories INTEGER NULL,
    has_sanitary_products INTEGER NULL,
    has_foundation INTEGER NULL,
    has_mascara INTEGER NULL,
    has_lipstick INTEGER NULL,
    has_micellar_water INTEGER NULL,
    has_cotton_pads INTEGER NULL,
    has_charger INTEGER NULL,
    has_powerbank INTEGER NULL,
    has_headphones INTEGER NULL,
    has_laptop INTEGER NULL,
    has_tablet INTEGER NULL,
    has_camera INTEGER NULL,
    has_watch INTEGER NULL,
    has_painkillers INTEGER NULL,
    has_bandages INTEGER NULL,
    has_insect_spray INTEGER NULL,
    has_bag INTEGER NULL,
    has_backpack INTEGER NULL,
    has_sunglasses INTEGER NULL,
    has_water_bottle INTEGER NULL,
    plane TEXT NULL,
    car_rental TEXT NULL,
    taxi_uber TEXT NULL,
    trains TEXT NULL,
    buses TEXT NULL,
    trams TEXT NULL,
    ships TEXT NULL,
    other_transport TEXT NULL,
    airport_to_hotel_transport TEXT NULL,
    hotel_to_airport_transport TEXT NULL,
    check_in_time TEXT NULL,
    check_out_time TEXT NULL,
    accommodation_notes TEXT NULL,
    attractions TEXT NULL,
    restaurants TEXT NULL,
    will_see TEXT NULL,
    will_taste TEXT NULL,
    will_do TEXT NULL,
    general_notes TEXT NULL,
    FOREIGN KEY (booked_holiday_id) REFERENCES booked_holidays(id)
  )`);

async function initData() {
  const populateHolidays = db.prepare(`
    INSERT INTO holidays VALUES (
      null,
      @image,
      @slug,
      @country,
      @city,
      @hotel_name,
      @date,
      @departure_city,
      @arrival_city,
      @food,
      @rating,
      @price,
      @hotel_features,
      @hotel_attractions,
      @hotel_image,
      @holiday_description,
      @hotel_description,
      @food_details
    )
  `);

  for (const holiday of holidays) {
    populateHolidays.run(holiday);
  }
}

initData();
