/* eslint-disable @typescript-eslint/no-unused-vars */
import { PlannedHoliday } from "@/app/booked-holidays/[bookedHolidaySlug]/page";

// eslint-disable-next-line @typescript-eslint/no-require-imports
const sql = require("better-sqlite3");
const db = sql("holidays.db");

export async function getPlannedHoliday(slug: string): Promise<PlannedHoliday> {
  return db
    .prepare(
      `SELECT 
        planned_holidays.main_budget,
        planned_holidays.insurance_budget,
        planned_holidays.shopping_budget,
        planned_holidays.souvenirs_budget,
        planned_holidays.activities_budget,
        planned_holidays.food_budget,
        planned_holidays.has_local_cash,
        planned_holidays.has_visa,
        planned_holidays.has_insurance,
        planned_holidays.has_vaccinations,
        planned_holidays.has_passport,
        planned_holidays.has_id_card,
        planned_holidays.has_tickets,
        planned_holidays.has_travel_invitation,
        planned_holidays.has_intl_driving_license,
        planned_holidays.has_payment_card,
        planned_holidays.has_tshirts,
        planned_holidays.has_pants,
        planned_holidays.has_underwear,
        planned_holidays.has_shoes,
        planned_holidays.has_jacket,
        planned_holidays.has_raincoat,
        planned_holidays.has_flip_flops,
        planned_holidays.has_headwear,
        planned_holidays.has_toothbrush,
        planned_holidays.has_toothpaste,
        planned_holidays.has_dental_floss,
        planned_holidays.has_shampoo,
        planned_holidays.has_conditioner,
        planned_holidays.has_hair_mask,
        planned_holidays.has_shower_gel,
        planned_holidays.has_soap,
        planned_holidays.has_deodorant,
        planned_holidays.has_perfume,
        planned_holidays.has_moisturizer,
        planned_holidays.has_spf_cream,
        planned_holidays.has_after_sun_cream,
        planned_holidays.has_razor,
        planned_holidays.has_shaving_foam,
        planned_holidays.has_brush,
        planned_holidays.has_hair_accessories,
        planned_holidays.has_sanitary_products,
        planned_holidays.has_foundation,
        planned_holidays.has_mascara,
        planned_holidays.has_lipstick,
        planned_holidays.has_micellar_water,
        planned_holidays.has_cotton_pads,
        planned_holidays.has_charger,
        planned_holidays.has_powerbank,
        planned_holidays.has_headphones,
        planned_holidays.has_laptop,
        planned_holidays.has_tablet,
        planned_holidays.has_camera,
        planned_holidays.has_watch,
        planned_holidays.has_painkillers,
        planned_holidays.has_bandages,
        planned_holidays.has_insect_spray,
        planned_holidays.has_bag,
        planned_holidays.has_backpack,
        planned_holidays.has_sunglasses,
        planned_holidays.has_water_bottle,
        planned_holidays.plane,
        planned_holidays.car_rental,
        planned_holidays.taxi_uber,
        planned_holidays.trains,
        planned_holidays.buses,
        planned_holidays.trams,
        planned_holidays.ships,
        planned_holidays.other_transport,
        planned_holidays.airport_to_hotel_transport,
        planned_holidays.hotel_to_airport_transport,
        planned_holidays.check_in_time,
        planned_holidays.check_out_time,
        planned_holidays.accommodation_notes,
        planned_holidays.attractions,
        planned_holidays.restaurants,
        planned_holidays.will_see,
        planned_holidays.will_taste,
        planned_holidays.will_do,
        planned_holidays.general_notes,
        booked_holidays.planned_holiday_id,
        booked_holidays.id,
        booked_holidays.user_id,
        booked_holidays.holiday_id,
        booked_holidays.booking_name,
        booked_holidays.booking_surname,
        booked_holidays.booking_email,
        booked_holidays.booking_phone,
        booked_holidays.holiday_members,
        booked_holidays.total_price,
        holidays.image,
        holidays.country,
        holidays.city,
        holidays.hotel_name,
        holidays.date,
        holidays.departure_city,
        holidays.arrival_city,
        holidays.food,
        holidays.hotel_features,
        holidays.hotel_attractions,
        holidays.hotel_image,
        holidays.holiday_description,
        holidays.hotel_description,
        holidays.food_details
      FROM booked_holidays
      INNER JOIN holidays
        ON booked_holidays.holiday_id = holidays.id
      LEFT JOIN planned_holidays 
        ON booked_holidays.planned_holiday_id = planned_holidays.id
      WHERE booked_holidays.id = ?`
    )
    .get(slug) as PlannedHoliday;
}

export function createPlannedHoliday(
  booked_holiday_id: number,
  main_budget: number | null,
  insurance_budget: number | null,
  shopping_budget: number | null,
  souvenirs_budget: number | null,
  activities_budget: number | null,
  food_budget: number | null,
  has_local_cash: boolean | null,
  has_visa: boolean | null,
  has_insurance: boolean | null,
  has_vaccinations: boolean | null,
  has_passport: boolean | null,
  has_id_card: boolean | null,
  has_tickets: boolean | null,
  has_travel_invitation: boolean | null,
  has_intl_driving_license: boolean | null,
  has_payment_card: boolean | null,
  has_tshirts: boolean | null,
  has_pants: boolean | null,
  has_underwear: boolean | null,
  has_shoes: boolean | null,
  has_jacket: boolean | null,
  has_raincoat: boolean | null,
  has_flip_flops: boolean | null,
  has_headwear: boolean | null,
  has_toothbrush: boolean | null,
  has_toothpaste: boolean | null,
  has_dental_floss: boolean | null,
  has_shampoo: boolean | null,
  has_conditioner: boolean | null,
  has_hair_mask: boolean | null,
  has_shower_gel: boolean | null,
  has_soap: boolean | null,
  has_deodorant: boolean | null,
  has_perfume: boolean | null,
  has_moisturizer: boolean | null,
  has_spf_cream: boolean | null,
  has_after_sun_cream: boolean | null,
  has_razor: boolean | null,
  has_shaving_foam: boolean | null,
  has_brush: boolean | null,
  has_hair_accessories: boolean | null,
  has_sanitary_products: boolean | null,
  has_foundation: boolean | null,
  has_mascara: boolean | null,
  has_lipstick: boolean | null,
  has_micellar_water: boolean | null,
  has_cotton_pads: boolean | null,
  has_charger: boolean | null,
  has_powerbank: boolean | null,
  has_headphones: boolean | null,
  has_laptop: boolean | null,
  has_tablet: boolean | null,
  has_camera: boolean | null,
  has_watch: boolean | null,
  has_painkillers: boolean | null,
  has_bandages: boolean | null,
  has_insect_spray: boolean | null,
  has_bag: boolean | null,
  has_backpack: boolean | null,
  has_sunglasses: boolean | null,
  has_water_bottle: boolean | null,
  plane: string | null,
  car_rental: string | null,
  taxi_uber: string | null,
  trains: string | null,
  buses: string | null,
  trams: string | null,
  ships: string | null,
  other_transport: string | null,
  airport_to_hotel_transport: string | null,
  hotel_to_airport_transport: string | null,
  check_in_time: string | null,
  check_out_time: string | null,
  accommodation_notes: string | null,
  attractions: string | null,
  restaurants: string | null,
  will_see: string | null,
  will_taste: string | null,
  will_do: string | null,
  general_notes: string | null
) {
  // insert new record into planned_holiday
  const newPlannedHolidayRow = db
    .prepare("INSERT INTO planned_holidays (booked_holiday_id) VALUES (?)")
    .run(booked_holiday_id);

  // id of new record
  const rowId = newPlannedHolidayRow.lastInsertRowid;

  const section1 = db
    .prepare(
      "UPDATE planned_holidays SET main_budget = ?, insurance_budget = ?, shopping_budget = ?, souvenirs_budget = ?, activities_budget = ?, food_budget = ?, has_local_cash = ? WHERE id = ?"
    )
    .run(
      main_budget,
      insurance_budget,
      shopping_budget,
      souvenirs_budget,
      activities_budget,
      food_budget,
      has_local_cash,
      rowId
    );

  const section2 = db
    .prepare(
      "UPDATE planned_holidays SET has_visa = ?, has_insurance = ?, has_vaccinations = ?, has_passport = ?, has_id_card = ?, has_tickets = ?, has_travel_invitation = ?, has_intl_driving_license = ?, has_payment_card = ? WHERE id = ?"
    )
    .run(
      has_visa,
      has_insurance,
      has_vaccinations,
      has_passport,
      has_id_card,
      has_tickets,
      has_travel_invitation,
      has_intl_driving_license,
      has_payment_card,
      rowId
    );

  const section3 = db
    .prepare(
      `UPDATE planned_holidays SET 
      has_tshirts = ?, 
      has_pants = ?, 
      has_underwear = ?, 
      has_shoes = ?, 
      has_jacket = ?, 
      has_raincoat = ?, 
      has_flip_flops = ?, 
      has_headwear = ?, 
      has_toothbrush = ?, 
      has_toothpaste = ?, 
      has_dental_floss = ?, 
      has_shampoo = ?, 
      has_conditioner = ?, 
      has_hair_mask = ?, 
      has_shower_gel = ?, 
      has_soap = ?, 
      has_deodorant = ?, 
      has_perfume = ?, 
      has_moisturizer = ?, 
      has_spf_cream = ?, 
      has_after_sun_cream = ?, 
      has_razor = ?, 
      has_shaving_foam = ?, 
      has_brush = ?, 
      has_hair_accessories = ?, 
      has_sanitary_products = ?, 
      has_foundation = ?, 
      has_mascara = ?, 
      has_lipstick = ?, 
      has_micellar_water = ?, 
      has_cotton_pads = ?, 
      has_charger = ?, 
      has_powerbank = ?, 
      has_headphones = ?, 
      has_laptop = ?, 
      has_tablet = ?, 
      has_camera = ?, 
      has_watch = ?, 
      has_painkillers = ?, 
      has_bandages = ?, 
      has_insect_spray = ?, 
      has_bag = ?, 
      has_backpack = ?, 
      has_sunglasses = ?, 
      has_water_bottle = ? 
    WHERE id = ?`
    )
    .run(
      has_tshirts,
      has_pants,
      has_underwear,
      has_shoes,
      has_jacket,
      has_raincoat,
      has_flip_flops,
      has_headwear,
      has_toothbrush,
      has_toothpaste,
      has_dental_floss,
      has_shampoo,
      has_conditioner,
      has_hair_mask,
      has_shower_gel,
      has_soap,
      has_deodorant,
      has_perfume,
      has_moisturizer,
      has_spf_cream,
      has_after_sun_cream,
      has_razor,
      has_shaving_foam,
      has_brush,
      has_hair_accessories,
      has_sanitary_products,
      has_foundation,
      has_mascara,
      has_lipstick,
      has_micellar_water,
      has_cotton_pads,
      has_charger,
      has_powerbank,
      has_headphones,
      has_laptop,
      has_tablet,
      has_camera,
      has_watch,
      has_painkillers,
      has_bandages,
      has_insect_spray,
      has_bag,
      has_backpack,
      has_sunglasses,
      has_water_bottle,
      rowId
    );

  const section4 = db
    .prepare(
      `UPDATE planned_holidays SET 
      plane = ?, 
      car_rental = ?, 
      taxi_uber = ?, 
      trains = ?, 
      buses = ?, 
      trams = ?, 
      ships = ?, 
      other_transport = ? 
    WHERE id = ?`
    )
    .run(
      plane,
      car_rental,
      taxi_uber,
      trains,
      buses,
      trams,
      ships,
      other_transport,
      rowId
    );

  const section5 = db
    .prepare(
      "UPDATE planned_holidays SET airport_to_hotel_transport = ?, hotel_to_airport_transport = ?, check_in_time = ?, check_out_time = ?, accommodation_notes = ? WHERE id = ?"
    )
    .run(
      airport_to_hotel_transport,
      hotel_to_airport_transport,
      check_in_time,
      check_out_time,
      accommodation_notes,
      rowId
    );

  const section6 = db
    .prepare("UPDATE planned_holidays SET attractions = ? WHERE id = ?")
    .run(attractions, rowId);

  const section7 = db
    .prepare("UPDATE planned_holidays SET restaurants = ? WHERE id = ?")
    .run(restaurants, rowId);

  const section8 = db
    .prepare(
      "UPDATE planned_holidays SET will_see = ?, will_taste = ?, will_do = ? WHERE id = ?"
    )
    .run(will_see, will_taste, will_do, rowId);

  const section9 = db
    .prepare("UPDATE planned_holidays SET general_notes = ? WHERE id = ?")
    .run(general_notes, rowId);

  // update planned_holiday_id column in booked_holidays table with newly created rowId
  db.prepare(
    "UPDATE booked_holidays SET planned_holiday_id = (?) WHERE id = (?)"
  ).run(rowId, booked_holiday_id);

  // .prepare(
  //   `INSERT INTO planned_holidays (
  //   booked_holiday_id,
  //   main_budget,
  //   insurance_budget,
  //   shopping_budget,
  //   souvenirs_budget,
  //   activities_budget,
  //   food_budget,
  //   has_local_cash,
  //   has_visa,
  //   has_insurance,
  //   has_vaccinations,
  //   has_passport,
  //   has_id_card,
  //   has_tickets,
  //   has_travel_invitation,
  //   has_intl_driving_license,
  //   has_payment_card,
  //   has_tshirts,
  //   has_pants,
  //   has_underwear,
  //   has_shoes,
  //   has_jacket,
  //   has_raincoat,
  //   has_flip_flops,
  //   has_headwear,
  //   has_toothbrush,
  //   has_toothpaste,
  //   has_dental_floss,
  //   has_shampoo,
  //   has_conditioner,
  //   has_hair_mask,
  //   has_shower_gel,
  //   has_soap,
  //   has_deodorant,
  //   has_perfume,
  //   has_moisturizer,
  //   has_spf_cream,
  //   has_after_sun_cream,
  //   has_razor,
  //   has_shaving_foam,
  //   has_brush,
  //   has_hair_accessories,
  //   has_sanitary_products,
  //   has_foundation,
  //   has_mascara,
  //   has_lipstick,
  //   has_micellar_water,
  //   has_cotton_pads,
  //   has_charger,
  //   has_powerbank,
  //   has_headphones,
  //   has_laptop,
  //   has_tablet,
  //   has_camera,
  //   has_watch,
  //   has_painkillers,
  //   has_bandages,
  //   has_insect_spray,
  //   has_bag,
  //   has_backpack,
  //   has_sunglasses,
  //   has_water_bottle,
  //   plane,
  //   car_rental,
  //   taxi_uber,
  //   trains,
  //   buses,
  //   trams,
  //   ships,
  //   other_transport,
  //   airport_to_hotel_transport,
  //   hotel_to_airport_transport,
  //   check_in_time,
  //   check_out_time,
  //   accommodation_notes,
  //   attractions,
  //   restaurants,
  //   will_see,
  //   will_taste,
  //   will_do,
  //   general_notes
  // ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`
  // )
  // .run(
  //   booked_holiday_id,
  //   main_budget,
  //   insurance_budget,
  //   shopping_budget,
  //   souvenirs_budget,
  //   activities_budget,
  //   food_budget,
  //   has_local_cash,
  //   has_visa,
  //   has_insurance,
  //   has_vaccinations,
  //   has_passport,
  //   has_id_card,
  //   has_tickets,
  //   has_travel_invitation,
  //   has_intl_driving_license,
  //   has_payment_card,
  //   has_tshirts,
  //   has_pants,
  //   has_underwear,
  //   has_shoes,
  //   has_jacket,
  //   has_raincoat,
  //   has_flip_flops,
  //   has_headwear,
  //   has_toothbrush,
  //   has_toothpaste,
  //   has_dental_floss,
  //   has_shampoo,
  //   has_conditioner,
  //   has_hair_mask,
  //   has_shower_gel,
  //   has_soap,
  //   has_deodorant,
  //   has_perfume,
  //   has_moisturizer,
  //   has_spf_cream,
  //   has_after_sun_cream,
  //   has_razor,
  //   has_shaving_foam,
  //   has_brush,
  //   has_hair_accessories,
  //   has_sanitary_products,
  //   has_foundation,
  //   has_mascara,
  //   has_lipstick,
  //   has_micellar_water,
  //   has_cotton_pads,
  //   has_charger,
  //   has_powerbank,
  //   has_headphones,
  //   has_laptop,
  //   has_tablet,
  //   has_camera,
  //   has_watch,
  //   has_painkillers,
  //   has_bandages,
  //   has_insect_spray,
  //   has_bag,
  //   has_backpack,
  //   has_sunglasses,
  //   has_water_bottle,
  //   plane,
  //   car_rental,
  //   taxi_uber,
  //   trains,
  //   buses,
  //   trams,
  //   ships,
  //   other_transport,
  //   airport_to_hotel_transport,
  //   hotel_to_airport_transport,
  //   check_in_time,
  //   check_out_time,
  //   accommodation_notes,
  //   attractions,
  //   restaurants,
  //   will_see,
  //   will_taste,
  //   will_do,
  //   general_notes
  // );
}

export function editPlannedHoliday(
  planned_holiday_id: number,
  main_budget: number | null,
  insurance_budget: number | null,
  shopping_budget: number | null,
  souvenirs_budget: number | null,
  activities_budget: number | null,
  food_budget: number | null,
  has_local_cash: boolean | null,
  has_visa: boolean | null,
  has_insurance: boolean | null,
  has_vaccinations: boolean | null,
  has_passport: boolean | null,
  has_id_card: boolean | null,
  has_tickets: boolean | null,
  has_travel_invitation: boolean | null,
  has_intl_driving_license: boolean | null,
  has_payment_card: boolean | null,
  has_tshirts: boolean | null,
  has_pants: boolean | null,
  has_underwear: boolean | null,
  has_shoes: boolean | null,
  has_jacket: boolean | null,
  has_raincoat: boolean | null,
  has_flip_flops: boolean | null,
  has_headwear: boolean | null,
  has_toothbrush: boolean | null,
  has_toothpaste: boolean | null,
  has_dental_floss: boolean | null,
  has_shampoo: boolean | null,
  has_conditioner: boolean | null,
  has_hair_mask: boolean | null,
  has_shower_gel: boolean | null,
  has_soap: boolean | null,
  has_deodorant: boolean | null,
  has_perfume: boolean | null,
  has_moisturizer: boolean | null,
  has_spf_cream: boolean | null,
  has_after_sun_cream: boolean | null,
  has_razor: boolean | null,
  has_shaving_foam: boolean | null,
  has_brush: boolean | null,
  has_hair_accessories: boolean | null,
  has_sanitary_products: boolean | null,
  has_foundation: boolean | null,
  has_mascara: boolean | null,
  has_lipstick: boolean | null,
  has_micellar_water: boolean | null,
  has_cotton_pads: boolean | null,
  has_charger: boolean | null,
  has_powerbank: boolean | null,
  has_headphones: boolean | null,
  has_laptop: boolean | null,
  has_tablet: boolean | null,
  has_camera: boolean | null,
  has_watch: boolean | null,
  has_painkillers: boolean | null,
  has_bandages: boolean | null,
  has_insect_spray: boolean | null,
  has_bag: boolean | null,
  has_backpack: boolean | null,
  has_sunglasses: boolean | null,
  has_water_bottle: boolean | null,
  plane: string | null,
  car_rental: string | null,
  taxi_uber: string | null,
  trains: string | null,
  buses: string | null,
  trams: string | null,
  ships: string | null,
  other_transport: string | null,
  airport_to_hotel_transport: string | null,
  hotel_to_airport_transport: string | null,
  check_in_time: string | null,
  check_out_time: string | null,
  accommodation_notes: string | null,
  attractions: string | null,
  restaurants: string | null,
  will_see: string | null,
  will_taste: string | null,
  will_do: string | null,
  general_notes: string | null
) {
  const updateQuery = `
    UPDATE planned_holidays SET
      main_budget = ?, 
      insurance_budget = ?, 
      shopping_budget = ?, 
      souvenirs_budget = ?, 
      activities_budget = ?, 
      food_budget = ?, 
      has_local_cash = ?, 
      has_visa = ?, 
      has_insurance = ?, 
      has_vaccinations = ?, 
      has_passport = ?, 
      has_id_card = ?, 
      has_tickets = ?, 
      has_travel_invitation = ?, 
      has_intl_driving_license = ?, 
      has_payment_card = ?, 
      has_tshirts = ?, 
      has_pants = ?, 
      has_underwear = ?, 
      has_shoes = ?, 
      has_jacket = ?, 
      has_raincoat = ?, 
      has_flip_flops = ?, 
      has_headwear = ?, 
      has_toothbrush = ?, 
      has_toothpaste = ?, 
      has_dental_floss = ?, 
      has_shampoo = ?, 
      has_conditioner = ?, 
      has_hair_mask = ?, 
      has_shower_gel = ?, 
      has_soap = ?, 
      has_deodorant = ?, 
      has_perfume = ?, 
      has_moisturizer = ?, 
      has_spf_cream = ?, 
      has_after_sun_cream = ?, 
      has_razor = ?, 
      has_shaving_foam = ?, 
      has_brush = ?, 
      has_hair_accessories = ?, 
      has_sanitary_products = ?, 
      has_foundation = ?, 
      has_mascara = ?, 
      has_lipstick = ?, 
      has_micellar_water = ?, 
      has_cotton_pads = ?, 
      has_charger = ?, 
      has_powerbank = ?, 
      has_headphones = ?, 
      has_laptop = ?, 
      has_tablet = ?, 
      has_camera = ?, 
      has_watch = ?, 
      has_painkillers = ?, 
      has_bandages = ?, 
      has_insect_spray = ?, 
      has_bag = ?, 
      has_backpack = ?, 
      has_sunglasses = ?, 
      has_water_bottle = ?, 
      plane = ?, 
      car_rental = ?, 
      taxi_uber = ?, 
      trains = ?, 
      buses = ?, 
      trams = ?, 
      ships = ?, 
      other_transport = ?, 
      airport_to_hotel_transport = ?, 
      hotel_to_airport_transport = ?, 
      check_in_time = ?, 
      check_out_time = ?, 
      accommodation_notes = ?, 
      attractions = ?, 
      restaurants = ?, 
      will_see = ?, 
      will_taste = ?, 
      will_do = ?, 
      general_notes = ?
    WHERE id = ?`;

  db.prepare(updateQuery).run(
    main_budget,
    insurance_budget,
    shopping_budget,
    souvenirs_budget,
    activities_budget,
    food_budget,
    has_local_cash,
    has_visa,
    has_insurance,
    has_vaccinations,
    has_passport,
    has_id_card,
    has_tickets,
    has_travel_invitation,
    has_intl_driving_license,
    has_payment_card,
    has_tshirts,
    has_pants,
    has_underwear,
    has_shoes,
    has_jacket,
    has_raincoat,
    has_flip_flops,
    has_headwear,
    has_toothbrush,
    has_toothpaste,
    has_dental_floss,
    has_shampoo,
    has_conditioner,
    has_hair_mask,
    has_shower_gel,
    has_soap,
    has_deodorant,
    has_perfume,
    has_moisturizer,
    has_spf_cream,
    has_after_sun_cream,
    has_razor,
    has_shaving_foam,
    has_brush,
    has_hair_accessories,
    has_sanitary_products,
    has_foundation,
    has_mascara,
    has_lipstick,
    has_micellar_water,
    has_cotton_pads,
    has_charger,
    has_powerbank,
    has_headphones,
    has_laptop,
    has_tablet,
    has_camera,
    has_watch,
    has_painkillers,
    has_bandages,
    has_insect_spray,
    has_bag,
    has_backpack,
    has_sunglasses,
    has_water_bottle,
    plane,
    car_rental,
    taxi_uber,
    trains,
    buses,
    trams,
    ships,
    other_transport,
    airport_to_hotel_transport,
    hotel_to_airport_transport,
    check_in_time,
    check_out_time,
    accommodation_notes,
    attractions,
    restaurants,
    will_see,
    will_taste,
    will_do,
    general_notes,
    planned_holiday_id // The id to identify which holiday to update
  );
}
